name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version: [8, 11, 17, 20]
    steps:
#       checkout
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.version }}

#       build project and run all tests & checks
      - name: Maven Verify
        run: mvn -B clean verify

#       Upload code coverage report to Codecov
      - name: Test Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}